# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI con Java y Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  calculadora-build:
    name: Compilando
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
    - uses: actions/checkout@v2 # This action checks-out your repository under $GITHUB_WORKSPACE, so your workflow can access it.
    - name: Configurar JDK 1.8
      uses: actions/setup-java@v1  # This action sets up a java environment for use in actions.
      with:
        java-version: 1.8
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build with Maven
      run: mvn -B package --file pom.xml
